### ISSUE TITLE
在小米note1s机型上，搜索不到对应的蓝牙设备

### ISSUE THREAD

**Issue by CoolCsf** [AlexMofer/ProjectX#11]
使用的是printer项目，在小米note1说的项目上无法搜索到蓝牙设备。在nexus5x上可以正常使用
printer项目链接：https://github.com/AlexMofer/Printer

**Comment by AlexMofer** [comment]
就我所知，小米的ROM自己整了一套非官方的权限机制。有可能受其影响。在5X上面能够正常打印就行啦，本项目的重点是演示打印结果是否符合预期，而不在于蓝牙是否能够正常搜索与匹配。这个项目的重点是设备连接后的数据传输及处理，而不是设备之间如何连接。因此这不属于我的考虑范围，如果打印结果有问题，我会尽可能的帮忙。但现在手头也没有小票打印机，估计也帮不上忙。而蓝牙搜索匹配做适配的问题，就得交给你自行查找解决方案啦。相信你能办到的，加油！

**Comment by CoolCsf** [comment]
但是，我想自己调整和适配扫描与搜索，但尴尬的是，我没有找到扫描搜索的代码……方便告知一下吗？

**Comment by AlexMofer** [comment]
这个项目没有扫描与搜索代码，原理是：点击“测试蓝牙打印机”按钮，此时程序开启蓝牙（如果关闭的话）然后载入已配对的设备列表，选择一个设备，打印。如果手机没有配对过设备，那么列表也就如你说的，空的。所以应用内的扫描与配对就待你自行解决啦。你进设置里面的蓝牙，扫描并匹配一个设备，那么再进本演示程序，你就能找到他了。

**Comment by CoolCsf** [comment]
soga...原来如此，也就是说其实我之前列表是空的，其实不一定是rom的问题？只是因为我之前没配对过？5x没事可能是因为我用过其他扫描的demo配对过？。那如果我要在应用内进行扫描，您推荐是在哪个地方执行会更好呢？

Alex Mofer <notifications@github.com> 于2018年12月11日周二 下午2:42写道：

**Comment by AlexMofer** [comment]
没错，至于何时在应用内扫描，你可参考5X的蓝牙设置页面，匹配列表增加一个固定项，用于启动搜索页面。在搜索页面完成搜索与匹配，返回继续执行打印。

**Comment by CoolCsf** [comment]
好的，我明白了。非常感谢回答。

Alex Mofer <notifications@github.com> 于2018年12月11日周二 下午4:59写道：
