### ISSUE TITLE
更新数据时,notifyDataSetChanged 报错

### ISSUE THREAD

**Issue by erfei1129** [AlexMofer/ProjectX#12]
@Override
    public void onBindViewHolder(PagerViewHolder holder, int position) {
        if (getItemViewType(position) == 1) {
            ((PhotoHolder) holder).bindData(position);
        } else {
            ((VideoHolder) holder).bindData(position);
        }
    }
直接崩溃,报错位置是这里,ClassCastException

**Comment by AlexMofer** [comment]
非常感谢，报错的是这儿，但出错的地方不是这里，是由getItemViewType导致，你更新数据以后，getItemViewType与旧的子项类型对应不上，因此，子项被存在了错误的viewType集合中去了，而重用的时候，被拿出来，结果对不上号，就导致类型转换错误。
```
    public final void destroyItem(ViewGroup container, int position, @NonNull Object object) {
        //noinspection unchecked
        VH holder = (VH) object;
        container.removeView(holder.itemView);
        holder.isRecycled = true;
        holder.mPosition = POSITION_NONE;
        int viewType = getItemViewType(position);
        ArrayList<VH> recycleHolders = holderSparse.get(viewType, new ArrayList<VH>());
        recycleHolders.add(holder);
        holderSparse.put(viewType, recycleHolders);
        onViewRecycled(holder);
    }
```
临时解决方案：先将两种子类合并在一起，在类的内部进行业务逻辑区分（高耦合）。
今晚会修正并发布新版本，到时候记得更新。

**Comment by erfei1129** [comment]
谢谢!

**Comment by AlexMofer** [comment]
@erfei1129 已经更新，你试试，看修复了没。按理说应该是没问题了。

**Comment by erfei1129** [comment]
还是不行哎。一刷新就崩溃，还是原来的位置
