### ISSUE TITLE
还是之前的问题,更新了依赖,还是不行

### ISSUE THREAD

**Issue by erfei1129** [AlexMofer/ProjectX#13]
@Override
    public void onBindViewHolder(PagerViewHolder holder, int position) {
        if (getItemViewType(position) == 1) {
            ((PhotoHolder) holder).bindData(position);
        } else {
            ((VideoHolder) holder).bindData(position);
        }
    }
这里还是会报错,类型转换异常.

**Comment by AlexMofer** [comment]
呃，我再排查一下。

**Comment by AlexMofer** [comment]
过于自信，只看到了最明显的问题，没发现一个较为隐藏的，已经修改并完完全全验证，晚上发布修复版本。

**Comment by AlexMofer** [comment]
试试新发布的版本：implementation 'am.util:viewpager:1.1.0'

**Comment by erfei1129** [comment]
只是一个类型的话,没问题, 两个类型的话,还是会出问题,但是没有报错;
服用View会出现个别白屏.

**Comment by AlexMofer** [comment]
@erfei1129 你先不要绑定业务逻辑的数据，比如先试试设置不同背景。如果没有问题，那么控件的基础逻辑已经不存在问题了。然后接下来就是处理业务逻辑中的数据问题，问题就在数据绑定上了。数据有没有对应正确。
目前我的测试代码已经完全使用了两种不同的类型（两个不同的子类），经过一系列操作，未发现存在复用的问题了。你可以下载源码试一下。
关键点，需要你排查一下到底问题出现在复用上，还是出现在数据绑定上，还是复用的View未处理好重置的问题（会从父视图移除再重新添加）。
