### ISSUE TITLE
怎麼取得印表機狀態??

### ISSUE THREAD

**Issue by OwenChen0911** [AlexMofer/ProjectX#14]
我看了源碼，PrinterWriter裡有一個 write指令

我試著用 write(PrintCommands.realTimeStatusTransmission(1));

但怎麼取得印表機狀態呢?? 謝謝

**Comment by AlexMofer** [comment]
这个指令虽然写了，但是没有测试。
从指令标准上来看：
·The printer transmits the current status. Each status is represented by
one-byte data.
打印机会返回一字节的状态数据，具体的数据格式，你需要参考一下指令文档。由于手头没有打印机了，所以该项目已基本停止维护了。
https://github.com/AlexMofer/Printer/blob/master/Commande%20ESCPOS.pdf

**Comment by OwenChen0911** [comment]
那再請教個問題，你只有ByteArrayOutputStream

沒有實作  ByteArrayInputStream???

**Comment by AlexMofer** [comment]
是的，业务逻辑里只对打印机发送数据，不做接受数据，因此input就全部省略了。你需要输入的情况，则需要自己手动建立Socket进行网络输入输出交互了。

**Comment by AlexMofer** [comment]
后续我这边增加一个暴露Input出来的接口，再发布一个版本。
