### ISSUE TITLE
打印图片一直乱码什么原因呢？调整了能调整的参数，还是一直乱码

### ISSUE THREAD

**Issue by miaomiao666666** [AlexMofer/ProjectX#15]

**Comment by miaomiao666666** [comment]
二维码能正常生成，就是打印图片乱码

**Comment by AlexMofer** [comment]
抱歉才看到，小票打印机的缓存很小的，图片数据流过大就会乱码，你先打印非常小的小图看看，一步步调大，同时抓一下打印图允许的最大数据流，找到临界点，然后把图片切割成几部分进行打印。

**Comment by miaomiao666666** [comment]
调整成很小的图就什么都打印不出来

**Comment by AlexMofer** [comment]
不一定是打印二维码，你可以先试试打印纯黑的小图，定位到问题所在，我之前也遇到过，有些差的机子，图片超过40×40就乱码了
