### ISSUE TITLE
有没有能过获取打印机信息的方法，根据打印机宽度自动适配

### ISSUE THREAD

**Issue by iwalking11** [AlexMofer/ProjectX#2]
你好，有没有能过获取打印机信息的方法，能根据打印机宽度自动适配，而不是手动输入。
我现在有这么个需求，使用无驱打印或者蓝牙打印的时候，能够根据连接的设备自动适配宽度,判断是80mm还是58mm，不知道有没有好的解决方案

**Comment by AlexMofer** [comment]
木有找到查询打印机纸张类型或者宽度的ESC/POS命令啊，翻遍了EPSON的官网也木有介绍。心有余力不足，只能靠手动。
