### ISSUE TITLE
Error:Could not find am.widget:circleprogressbar:1.0.2.

### ISSUE THREAD

**Issue by Looper-01** [AlexMofer/ProjectX#3]
gradle拉取失败

edit:
直接import demo里面的module解决了，哈哈，的确很赞，超高配置性！

**Comment by AlexMofer** [comment]
昨晚试了下重新拉取主项目，也拉取不动，但报的不是这个错误，主项目已经被我整得太大了，但其实各个控件基本都有分项目，但主要还是用这个项目来维护。

分项目位置：[CircleProgressBar](https://github.com/AlexMofer/CircleProgressBar)
