### ISSUE TITLE
关于RecyclePagerAdapter在onConfigurationChanged时view没有重新布局的问题

### ISSUE THREAD

**Issue by luke1989** [AlexMofer/ProjectX#5]
RecyclePagerAdapter 这个类挺好的，有效的实现了view的重复利用
但是也有一个问题，当onConfigurationChanged时由于重复利用了之前的view
导致之前的view属性没有重新map，会导致pager里面的view没有对齐的问题

**Comment by AlexMofer** [comment]
感谢提示，这个还真没有考虑到。回头给其增加一个onConfigurationChanged方法，来处理缓存的已销毁子项的Configuration改变，在Activity的onConfigurationChanged方法中开发者手动调用，以及重写一个ViewPager在其onConfigurationChanged方法中控件主动调用。

**Comment by AlexMofer** [comment]
已发布27.0.0及27.0.1，已修复该问题，使用中注意调用Adapter的onConfigurationChanged方法。或使用RecycleViewPager。
