### ISSUE TITLE
能支持四个圆角的radius各不一样吗？

### ISSUE THREAD

**Issue by LwkCoder** [AlexMofer/ProjectX#7]

**Comment by AlexMofer** [comment]
你指的是哪个？
ShapeImageView是支持圆角不一样的，但你需要自定义一个ImageShape，可以参考RoundRectImageShape实现。
CornerDrawable是不支持不同圆角，其涉及到很复杂的突出尖角的位置计算方式，因此没做不同radius的支持，也不打算做，你可以自行修改出来。

**Comment by LwkCoder** [comment]
@AlexMofer 好的 我试试看  谢谢你了 从你的projectX中受益不少！
