### ISSUE TITLE
Gradienttabstrip适配器调用notifyDataSetChanged()后选中的位置错误

### ISSUE THREAD

**Issue by LwkCoder** [AlexMofer/ProjectX#8]
Gradienttabstrip默认选中的tab下标为0（即ViewPager中第一页），然后调用对应的Adapter.notifyDataSetChanged()后，Gradienttabstrip选中的tab变为第二个了，但是ViewPager里没有变为第二页。
复现方式：
在Demo里添加adapter.notifyDataSetChanged()即可。
`
tvTitle.postDelayed(new Runnable()
        {
            @Override
            public void run()
            {
                adapter.notifyDataSetChanged();
            }
        },2000);
`

**Comment by AlexMofer** [comment]
调用控件的invalidatePosition()方法强制刷新选中。
