### ISSUE TITLE
无法打印虚线，并且打印直线的时候没有打印完整

### ISSUE THREAD

**Issue by ByteRax** [AlexMofer/ProjectX#9]
RT
![qq 20180514004224](https://user-images.githubusercontent.com/5227840/39969540-c70ff13c-570f-11e8-8683-e03cd38105fb.jpg)

红色圈起来的 线条就是，调用的printLine

**Comment by AlexMofer** [comment]
打印一条横线或者一条虚线在EPSON文档中没有找到有标准的命令。
然而需求上需要实现，因此我们采用一些巧妙的方法来实现。
printLine方法 不过是帮你打印了刚刚好占满一行的"─"符号，此横线为制表符，无法打印出来可尝试使用"-"符号替代，但你得自行计算一行能占满多少个符号。（标准的制表符打印不出来，是不是另有隐情？）
至于虚线，" "与"-"间隔交替不就完成了吗？甚至你还可以创造出更多的dash样式，比如"─ - ─ - ─ - ─"。

**Comment by ByteRax** [comment]
@AlexMofer 谢谢大佬回复，非常感谢，有思路了。
